Fixes #916 vignettes use image of report preventing messed up style (#917)
* Fixes #916 vignettes use image of report preventing messed up style

* Prevent check errors from cleaning figures/ after vignette run

However, figures need to be copied over to the folder to be exported in webpage documentation (otherwise, empty image due to broken link)

* Remove code_folding option from vignette

Error: processing vignette 'qualification-workflow.Rmd' failed with diagnostics:
You must use a theme when specifying the 'code_folding' option